// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/example/example.proto

/*
Package staff is a generated protocol buffer package.

It is generated from these files:

	test/example/example.proto

It has these top-level messages:

	Staff
	StringMessage
	User
*/
package tagReset

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Staff struct {
	ID      string       `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name    string       `protobuf:"bytes,2,opt,name=Name" json:"name,omitempty" xml:"name,omitempty"`
	Age     int64        `protobuf:"varint,3,opt,name=Age" json:"age,omitempty" xml:"age,omitempty"`
	MyClass *Staff_Class `protobuf:"bytes,4,opt,name=MyClass" json:"class,omitempty" xml:"class,omitempty"`
}

func (m *Staff) Reset()                    { *m = Staff{} }
func (m *Staff) String() string            { return proto.CompactTextString(m) }
func (*Staff) ProtoMessage()               {}
func (*Staff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Staff) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Staff) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Staff) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Staff) GetMyClass() *Staff_Class {
	if m != nil {
		return m.MyClass
	}
	return nil
}

type Staff_Class struct {
	ID   string `protobuf:"bytes,1,opt,name=ID" json:"id,omitempty" xml:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=Type" json:"type,omitempty" xml:"type,omitempty"`
}

func (m *Staff_Class) Reset()                    { *m = Staff_Class{} }
func (m *Staff_Class) String() string            { return proto.CompactTextString(m) }
func (*Staff_Class) ProtoMessage()               {}
func (*Staff_Class) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Staff_Class) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Staff_Class) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type StringMessage struct {
	// required
	Value string   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty" valid:"required"`
	User  *User    `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
	Names []string `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
}

func (m *StringMessage) Reset()                    { *m = StringMessage{} }
func (m *StringMessage) String() string            { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()               {}
func (*StringMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *StringMessage) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type StringMessage_Member struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Age  int64  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *StringMessage_Member) Reset()                    { *m = StringMessage_Member{} }
func (m *StringMessage_Member) String() string            { return proto.CompactTextString(m) }
func (*StringMessage_Member) ProtoMessage()               {}
func (*StringMessage_Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *StringMessage_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StringMessage_Member) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type User struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty" valid:"required"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*Staff)(nil), "staff.Staff")
	proto.RegisterType((*Staff_Class)(nil), "staff.Staff.Class")
	proto.RegisterType((*StringMessage)(nil), "staff.StringMessage")
	proto.RegisterType((*StringMessage_Member)(nil), "staff.StringMessage.Member")
	proto.RegisterType((*User)(nil), "staff.User")
}

func init() { proto.RegisterFile("test/example/example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x6c, 0x52, 0x75, 0x82, 0x22, 0x83, 0x87, 0x25, 0x17, 0x43, 0x4e, 0x01, 0x65,
	0x85, 0xfa, 0x04, 0x62, 0x2f, 0x3d, 0xc4, 0xc3, 0x56, 0x1f, 0x60, 0x0b, 0xd3, 0x20, 0x24, 0x6d,
	0xd8, 0x5d, 0xc5, 0xbe, 0x83, 0x0f, 0xe0, 0xe3, 0xca, 0x4e, 0xda, 0xa0, 0xd0, 0xd3, 0x7c, 0xff,
	0x4c, 0xfe, 0xf9, 0x33, 0x0b, 0x45, 0x20, 0x1f, 0x1e, 0xe8, 0xcb, 0xf6, 0x43, 0x47, 0xc7, 0xaa,
	0x07, 0xb7, 0x0b, 0x3b, 0xcc, 0x7c, 0xb0, 0x9b, 0x4d, 0xf5, 0x23, 0x20, 0x5b, 0x45, 0xc2, 0x2b,
	0x48, 0x96, 0x0b, 0x25, 0x4a, 0x51, 0x5f, 0x98, 0x64, 0xb9, 0x40, 0x84, 0xf4, 0xc5, 0xf6, 0xa4,
	0x12, 0xee, 0x30, 0xe3, 0x35, 0xc8, 0xa7, 0x96, 0x94, 0x2c, 0x45, 0x2d, 0x4d, 0x44, 0xbc, 0x87,
	0xb3, 0x66, 0xff, 0xdc, 0x59, 0xef, 0x55, 0x5a, 0x8a, 0x3a, 0x9f, 0xa3, 0xe6, 0xc5, 0x9a, 0x97,
	0x6a, 0x9e, 0x98, 0xe3, 0x27, 0xc5, 0x1d, 0x64, 0x0c, 0xa7, 0xc2, 0x5e, 0xf7, 0xc3, 0x14, 0x16,
	0xb9, 0xfa, 0x16, 0x70, 0xb9, 0x0a, 0xee, 0x7d, 0xdb, 0x36, 0xe4, 0xbd, 0x6d, 0x09, 0x6f, 0x20,
	0xfb, 0xb4, 0xdd, 0x07, 0x1d, 0x8c, 0xa3, 0xc0, 0x5b, 0x48, 0xdf, 0x3c, 0x39, 0xf6, 0xe6, 0xf3,
	0xfc, 0x90, 0x1f, 0x5b, 0x86, 0x07, 0xd1, 0xb6, 0xb5, 0x3d, 0x79, 0x25, 0x4b, 0x19, 0x6d, 0x2c,
	0x0a, 0x0d, 0xb3, 0x86, 0xfa, 0x35, 0xb9, 0xe9, 0x52, 0xf1, 0xff, 0x52, 0xdb, 0x8e, 0xff, 0x23,
	0x4d, 0xc4, 0xaa, 0x1a, 0x63, 0xb0, 0x80, 0xf3, 0x58, 0xff, 0x38, 0x26, 0xbd, 0x9e, 0xf1, 0xdb,
	0x3e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x87, 0xe8, 0x5b, 0xc6, 0x79, 0x01, 0x00, 0x00,
}

